version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 160596073886.dkr.ecr.us-east-1.amazonaws.com
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-8)
      - echo "IMAGE_TAG=$IMAGE_TAG"
      - echo $IMAGE_TAG > image_tag.txt

  build:
    commands:
      - IMAGE_TAG=$(cat image_tag.txt)
      - echo "Build started on $(date)"
      - docker build -t flask-ecs-app:$IMAGE_TAG .
      - docker tag flask-ecs-app:$IMAGE_TAG 160596073886.dkr.ecr.us-east-1.amazonaws.com/flask-ecs-app:$IMAGE_TAG

  post_build:
    commands:
      - IMAGE_TAG=$(cat image_tag.txt)
      - echo "Post-build started on $(date)"
      - echo "Using image tag: $IMAGE_TAG"
      - docker images
      - echo "Pushing image to ECR..."
      - docker push 160596073886.dkr.ecr.us-east-1.amazonaws.com/flask-ecs-app:$IMAGE_TAG
      - docker tag 160596073886.dkr.ecr.us-east-1.amazonaws.com/flask-ecs-app:$IMAGE_TAG 160596073886.dkr.ecr.us-east-1.amazonaws.com/flask-ecs-app:latest
      - docker push 160596073886.dkr.ecr.us-east-1.amazonaws.com/flask-ecs-app:latest
      - printf '[{"name":"flask-ecs-app","imageUri":"160596073886.dkr.ecr.us-east-1.amazonaws.com/flask-ecs-app:%s"}]' $IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
