version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 160596073886.dkr.ecr.ap-south-1.amazonaws.com
      - echo "Setting image tag from Git commit ID..."
      

  build:
    commands:
      - echo Build started on `date`
      - echo Building Docker image...
      - docker build -t flask-ecs-app:$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)
      - docker tag flask-ecs-app:$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8) 160596073886.dkr.ecr.ap-south-1.amazonaws.com/flask-ecs-app:$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)

  post_build:
    commands:
      - echo Post-build started on `date`
      - echo Pushing Docker image to ECR...
      - docker push 160596073886.dkr.ecr.ap-south-1.amazonaws.com/flask-ecs-app:$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)
      - docker tag 160596073886.dkr.ecr.ap-south-1.amazonaws.com/flask-ecs-app:$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8) 160596073886.dkr.ecr.ap-south-1.amazonaws.com/flask-ecs-app:latest
      - docker push 160596073886.dkr.ecr.ap-south-1.amazonaws.com/flask-ecs-app:latest
      - echo Creating imagedefinitions.json for ECS deployment...
      - printf '[{"name":"flask-ecs-app","imageUri":"160596073886.dkr.ecr.ap-south-1.amazonaws.com/flask-ecs-app:%s"}]' $(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8) > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
