version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 160596073886.dkr.ecr.ap-south-1.amazonaws.com
      - echo "Setting image tag from Git commit ID..."
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-8)
      - echo "Image tag is $IMAGE_TAG"
      - echo $IMAGE_TAG > image_tag.txt

  build:
    commands:
      - IMAGE_TAG=$(cat image_tag.txt)
      - echo "Build started on $(date)"
      - echo "Building Docker image with tag $IMAGE_TAG..."
      - docker build -t flask-ecs-app:$IMAGE_TAG .
      - docker tag flask-ecs-app:$IMAGE_TAG 160596073886.dkr.ecr.ap-south-1.amazonaws.com/flask-ecs-app:$IMAGE_TAG

  post_build:
    commands:
      - IMAGE_TAG=$(cat image_tag.txt)
      - echo "Post-build started on $(date)"
      - echo "Pushing image with tag: $IMAGE_TAG"
      - docker push 160596073886.dkr.ecr.ap-south-1.amazonaws.com/flask-ecs-app:$IMAGE_TAG
      - docker tag 160596073886.dkr.ecr.ap-south-1.amazonaws.com/flask-ecs-app:$IMAGE_TAG 160596073886.dkr.ecr.ap-south-1.amazonaws.com/flask-ecs-app:latest
      - docker push 160596073886.dkr.ecr.ap-south-1.amazonaws.com/flask-ecs-app:latest
      - echo "Creating imagedefinitions.json for ECS deployment..."
      - printf '[{"name":"flask-ecs-app","imageUri":"160596073886.dkr.ecr.ap-south-1.amazonaws.com/flask-ecs-app:%s"}]' $IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
