version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 160596073886.dkr.ecr.us-east-1.amazonaws.com
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)
      - echo "IMAGE_TAG=$IMAGE_TAG"
      - echo $IMAGE_TAG > image_tag.txt

  build:
    commands:
      - IMAGE_TAG=$(cat image_tag.txt)
      - echo Build started on `date`
      - echo Building Docker image...
      - docker build -t flask-app-demo:$IMAGE_TAG .
      - docker tag flask-app-demo:$IMAGE_TAG 160596073886.dkr.ecr.us-east-1.amazonaws.com/flask-app-demo:$IMAGE_TAG
      - docker tag flask-app-demo:$IMAGE_TAG 160596073886.dkr.ecr.us-east-1.amazonaws.com/flask-app-demo:latest

  post_build:
    commands:
      - IMAGE_TAG=$(cat image_tag.txt)
      - echo Build completed on `date`
      - echo Pushing Docker images...
      - docker push 160596073886.dkr.ecr.us-east-1.amazonaws.com/flask-app-demo:$IMAGE_TAG
      - docker push 160596073886.dkr.ecr.us-east-1.amazonaws.com/flask-app-demo:latest
      - echo "Replacing <IMAGE_TAG> in task definition..."
      - sed "s|<IMAGE_TAG>|$IMAGE_TAG|g" taskdef.json > taskdef_rendered.json
      - echo Writing appspec file...
      - cat appspec.yaml

artifacts:
  files:
    - appspec.yaml
    - taskdef_rendered.json
