version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 160596073886.dkr.ecr.us-east-1.amazonaws.com
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)
      - echo "IMAGE_TAG=$IMAGE_TAG"
      - export IMAGE_TAG
      - REPOSITORY_URI=160596073886.dkr.ecr.us-east-1.amazonaws.com/flask-ecs-app
      - export REPOSITORY_URI

  build:
    commands:
      - echo Build started on $(date)
      - docker build -t flask-ecs-app:$IMAGE_TAG .
      - docker tag flask-ecs-app:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
      - docker tag flask-ecs-app:$IMAGE_TAG $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo Build completed on $(date)
      - docker images
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - echo Writing imagedefinitions.json...
      - printf '[{"name":"flask-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
